apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: green-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: green
      name: nginx
    spec:
      containers:
      - name: nginx
        image: gitlab.mytestlab.xyz:4567/docker/images/green-nginx
        imagePullPolicy: Always
        resources:
        ports: 
        - containerPort: 80
          name: http
      imagePullSecrets:
        - name: regsecret